#!/usr/bin/env bash


## Text formatting
blue=$(tput setaf 4)
yellow=$(tput setaf 3)
reset=$(tput sgr0)
bold=$(tput bold)

# pushit :: Push to Github from current directory
function pushit() {
  DATE=$(date '+%y%m%d-%H%M')
  git pull 2>&1
  git add . 2>&1
  git commit -m "${DATE}" 2>&1
  git push 2>&1
}

echo ""
echo "${bold}${yellow}syncing dotfiles${reset}"
echo ""
sleep 2

# sync macback-m1 & macback-intel dotfiles, excluding .bash_profile & .git
rsync -rtu --exclude '.bash_profile' --exclude '.git' ~/macback-m1/dotfiles/ ~/macback-intel/dotfiles/ --progress && rsync -rtu --exclude '.bash_profile' --exclude '.git' ~/macback-intel/dotfiles/ ~/macback-m1/dotfiles/ --progress

# sync macback-m1 dotfiles with system dotfiles since they should match, excluding .git
rsync -rtu --exclude '.git' ~/macback-m1/dotfiles/ ~/dotfiles/ --progress  && rsync -rtu --exclude '.git' ~/dotfiles/ ~/macback-m1/dotfiles/ --progress
sleep 2

echo ""
echo "${bold}${yellow}syncing Brewfiles${reset}"
echo ""
sleep 2

# sync Brewfile three different ways to insure all three are identical
rsync -rtu ~/macback-m1/Brewfile ~/macback-intel/Brewfile --progress && rsync -rtu ~/macback-intel/Brewfile ~/macback-m1/Brewfile --progress
rsync -rtu ~/homebrew-brewfile/Brewfile ~/macback-m1/Brewfile --progress && rsync -rtu ~/macback-m1/Brewfile ~/homebrew-brewfile/Brewfile --progress
rsync -rtu ~/homebrew-brewfile/Brewfile ~/macback-intel/Brewfile --progress && rsync -rtu ~/macback-intel/Brewfile ~/homebrew-brewfile/Brewfile --progress
sleep 2

echo ""
echo "${bold}${yellow}Pushing changes to Github${reset}"
echo ""
sleep 2


cd ~/macback-m1 && echo "" && echo "${bold}${blue}macback-m1${reset}" && sleep 2 && pushit && sleep 2 && cd ~/macback-intel && echo "" && echo "${bold}${blue}macback-intel${reset}" && sleep 2 && pushit && sleep 2 && cd ~/dotfiles && echo "" && echo "${bold}${blue}dotfiles${reset}" && sleep 2 && pushit && sleep 2 && cd ~/homebrew-brewfile && echo "" && echo "${bold}${blue}Brewfile${reset}" && sleep 2 && pushit && sleep 2
sleep 2

echo ""
echo "${bold}${yellow}sync completed!${reset}"
echo "sync completed: " `date "+%F %T"` >> ~/scripts/backup/backups.log
echo ""
